In [1]:
import numpy as np

### writing items into an array

In [4]:
# a simple definition for a dvd
dvd_collection = [None]* 15
class DVD:
    def __init__(self, name, release_year, director):
        self.name = name
        self.release_year = release_year
        self.director = director




    def __str__(self, ):
        return f'{self.name} directed by {self.director} released in {self.release_year}'
    
dvd1 = DVD('Inception', 2010, 'Christopher Nolan')
dvd2 = DVD('matrix', 1999, 'Lana Wachowski')
# dvd1.__str__()
# dvd2.__str__()
dvd_collection[0] = dvd1
dvd_collection[1] = dvd2
for dvd in dvd_collection:
    print(dvd)


Inception directed by Christopher Nolan released in 2010
matrix directed by Lana Wachowski released in 1999
None
None
None
None
None
None
None
None
None
None
None
None
None


In [5]:
l = [None] *4      # it is like [None, None, None, None]
print(len(l))

4


In [6]:
# array operation is writing element to them and reading from them
#lets add and put the 'Avengers' in 8th place of the array we just created
# Firstly, we need to actually create a DVD object for The Avengers.
dvd3 = DVD('The Avengers', 2012, 'Joss Whedon')

#Next, we'll put it into the 8th place of the Array. Remember, because we
# started numbering from 0, the index we want is 7.

dvd_collection[7] = dvd3
for dvd in dvd_collection:
    print(dvd)

Inception directed by Christopher Nolan released in 2010
matrix directed by Lana Wachowski released in 1999
None
None
None
None
None
The Avengers directed by Joss Whedon released in 2012
None
None
None
None
None
None
None


In [7]:
# lets put more dvds
dvd4 = DVD("The Incredibles", 2004, "Brad Bird")
dvd5 = DVD("Finding Dory", 2016, "Andrew Stanton")
dvd6 = DVD("The Lion King", 2019, "Jon Favreau")
dvd_collection[3] = dvd4
dvd_collection[9] = dvd5
dvd_collection[2] = dvd6
for dvd in dvd_collection:
    print(dvd)


Inception directed by Christopher Nolan released in 2010
matrix directed by Lana Wachowski released in 1999
The Lion King directed by Jon Favreau released in 2019
The Incredibles directed by Brad Bird released in 2004
None
None
None
The Avengers directed by Joss Whedon released in 2012
None
Finding Dory directed by Andrew Stanton released in 2016
None
None
None
None
None


In [9]:
dvd7 = DVD('Star Wars', 1977, 'George Lucas')
dvd_collection[3] = dvd7
for dvd in dvd_collection:
    print(dvd)


Inception directed by Christopher Nolan released in 2010
matrix directed by Lana Wachowski released in 1999
The Lion King directed by Jon Favreau released in 2019
Star Wars directed by George Lucas released in 1977
None
None
None
The Avengers directed by Joss Whedon released in 2012
None
Finding Dory directed by Andrew Stanton released in 2016
None
None
None
None
None


### reading items from an array with loop

In [11]:
for dvd in dvd_collection:
    print(f'the collection of dvds are :{dvd}')

the collection of dvds are :Inception directed by Christopher Nolan released in 2010
the collection of dvds are :matrix directed by Lana Wachowski released in 1999
the collection of dvds are :The Lion King directed by Jon Favreau released in 2019
the collection of dvds are :Star Wars directed by George Lucas released in 1977
the collection of dvds are :None
the collection of dvds are :None
the collection of dvds are :None
the collection of dvds are :The Avengers directed by Joss Whedon released in 2012
the collection of dvds are :None
the collection of dvds are :Finding Dory directed by Andrew Stanton released in 2016
the collection of dvds are :None
the collection of dvds are :None
the collection of dvds are :None
the collection of dvds are :None
the collection of dvds are :None


In [12]:
array = [None] * 6
array

[None, None, None, None, None, None]

In [13]:
print(len(array))

6


In [15]:
for i in range(3):
    array[i] = i * i
print(array)
print(len(array))


[0, 1, 4, None, None, None]
6


In [21]:
# The first three digits or the last fourth digits are consecutive 1s. The maximum number of consecutive 1s is 4.
def find_max_consecutive_ones():
    nums = [1, 1, 1, 0, 1, 1, 1, 1]
    max_consecutive = 0
    current_consecutive = 0
    for num in nums:
        if num == 1:
            current_consecutive += 1
            max_consecutive = max(current_consecutive, max_consecutive)
        else:
            current_consecutive = 0
    return max_consecutive
output = find_max_consecutive_ones()
output




4

In [24]:
# Given an array nums of integers, return how many of them contain an even number of digits.

nums = [12,345,2,6,7896]
count = 0
for num in nums:
    num = str(num)
    if len(num) % 2 == 0:
        count += 1
print(f'counts of numbers with even digits are:{count}')







counts of numbers with even digits are:2


In [14]:
# another approach to not consider each number as string
nums  = [3245, 546, 65, 234, 5678, 34, 2]
count = 0
digit_count = 0
for num in nums :
    while num != 0:
        digit = num % 10
        digit_count += 1
        num = num // 10
    if digit_count % 2 == 0:
        count += 1
print(count)



    

4


In [ ]:
# Given an integer array nums sorted in non-decreasing order, return an array of the squares of each number sorted in non-decreasing order.

In [34]:
nums = [-4,-1,0,3,10]
nums_new = []
for num in nums:
    num = (num**2)
    nums_new.append(num)
print(nums_new)
for i in nums_new:
    nums_new.sort()
print(nums_new)




[16, 1, 0, 9, 100]
[0, 1, 9, 16, 100]


In [ ]:
# quick sort algorithm in python
#1.Select an element from the array as the pivot. The choice of pivot can vary (e.g., first element, last element, middle element, random element).
#2.partitioning:
#2.1.elements less than the pivote are on the left
#2.2. element greater than the pivote are on the right
#3.recursively apply
#4.the recursion ends when the sub-array has zero or one element, which is inherently sorted.

In [2]:
def quick_sort(arr):
    if len(arr) <= 1:
        return arr
    pivot = arr[len(arr)//2]   # Choose the middle element as the pivot
    left = [x for x in arr if x < pivot]   # Elements less than the pivot
    middle = [x for x in arr if x == pivot]   # Elements equal to the pivot
    right = [x for x in arr if x > pivot]   # Elements greater than the pivot

     # Recursively apply quick_sort to the left and right sub-arrays
    return quick_sort(left) + middle + quick_sort(right)
arr = [3, 6, 8, 10, 1, 2, 1]
sorted_arr = quick_sort(arr)
print(f'the original array is {arr}')
print(f'the sorted array is {sorted_arr}')

the original array is [3, 6, 8, 10, 1, 2, 1]
the sorted array is [1, 1, 2, 3, 6, 8, 10]


In [6]:
# insert in end of an array
arr = np.array([2,3,4,5,6,7])
arr[-1] = 8
print(arr)

[2 3 4 5 6 8]


In [16]:
# Declare an integer list with a capacity of 6 elements
int_list = [None] * 6
length = 0

# Add 3 elements to the list
for i in range(3, 6):
    int_list[length] = i
    length+=1
print(int_list)


[3, 4, 5, None, None, None]


In [18]:
# Add 3 elements in end of the list

int_list_ = [None] * 6
lenght = -1
for i in range(4,8):
    int_list_[length] = i
    length -= 1
print(int_list_)

[None, None, 7, 6, 5, 4]


In [26]:
# duplicate zeros
#Given a fixed-length integer array arr, duplicate each occurrence of zero, shifting the remaining elements to the right.

input_arr = [1,0,2,3,0,4,5]
s = 0
d = 0
N = len(input_arr)
# output = [0] * N

while s < N:
    if d >= N:
        break
    if input_arr[s] == 0:
        if d < N:
            output[d] = 0
        d += 1
        if d < N:
            output[d] = 0
    else:
        if d < N:
            output[d] = input_arr[s]
    d += 1
    s += 1

print(output)

    

[1, 0, 0, 2, 3, 0, 0]


In [29]:
input_array = [4, 0, 6, 7, 0,7]
output_array = [4, 0, 0, 6, 7, 0]
#output_array <= len(input_array)
N = len(input_array)
s = 0
d = 0
if input_array[s] != 0:
    output_array[d] = input_array[s]
    s+=1
    d+=1
else:
    output_array[d] = 0
    d+=1
    output_array[d] = 0
s+=1
d+=1
print(output_array)



[4, 0, 0, 6, 7, 0]


In [36]:
# You are given two integer arrays nums1 and nums2, sorted in non-decreasing order, and two integers m and n, representing the number of elements in nums1 and nums2 respectively.

#Merge nums1 and nums2 into a single array sorted in non-decreasing order.
nums1 = [1, 2, 3, 0, 0, 0]
nums2 = [2, 5, 6]

m = len(nums1)
n= len(nums2)
num = []

#output = [1, 2, 2, 3, 5, 6]
for i in nums1:
    if i != 0:
        num.append(i)
for j in nums2:
    if j!= 0:
        num.append(j)
for z in num:
    num.sort()
    
print(num)


[1, 2, 2, 3, 5, 6]


In [65]:
# Array Deletion
# deleting from the end of an array
def delet_element(arr):
    arr.remove(arr[-1])
    arr.remove(arr[len(arr)//2])

    return  arr



arr = [4,3,2,5,67,8]
arr1= delet_element(arr)
arr1



[4, 3, 5, 67]

In [64]:
list = [4,5,6,7,8]
list.remove(list[-1])
list

[4, 5, 6, 7]

In [72]:
#Given an integer array nums and an integer val, remove all occurrences of val in nums in-place. The order of the elements may be changed. Then return the number of elements in nums which are not equal to val.
nums = [3,2,2,3, 3, 3]
val = 3

#output = 2, [2,2,_, _]

count = 0
for i in nums:
    if val == i:
        count+=1
    
print(count)


4


In [80]:
def remove_occurances(arr):
    count = 0
    for i in arr:
        if val == i:
            count+=1
        else:
            continue
    return count


val = 3
arr = [3,4,5,6,7,8]
# arr = [1,2,3,4,5,3]
out = remove_occurances(arr)
out

1

In [19]:
#Given an integer array nums sorted in non-decreasing order, remove the duplicates in-place such that each unique element appears only once. The relative order of the elements should be kept the same. Then return the number of unique elements in nums.
# there is two approach for obtaining occurences of elements in a list:
# 1. using Counter from collections
#2. using dictionaries
# both approach give the occurences of each elements in a list

from collections import Counter
import numpy as np

nums = [1,1,1,2,2,3,3,3,4,4,4,5,6,7]
print(Counter(nums))



Counter({1: 3, 3: 3, 4: 3, 2: 2, 5: 1, 6: 1, 7: 1})


In [1]:
#2. using dictionaries
dict = {}  # define an empty dictionary
def find_duplicates(nums):
    for num in nums:
        if num in dict:
            dict[num] += 1
            # print(dict[num])
        else:
            dict[num] = 1
            # print(dict[num])
    return dict

nums = [1,1,1,2,2,3,3,3,4,4,4,5,6,7]

d = find_duplicates(nums)
d_keys = d.keys()

print(list(d_keys))

[1, 2, 3, 4, 5, 6, 7]


In [16]:
# find the smallest letter greater than target
#You are given an array of characters letters that is sorted in non-decreasing order, and a character target. There are at least two different characters in letters.

#Return the smallest character in letters that is lexicographically greater than target. If such a character does
#not exist, return the first character in letters.
# this function works if and only if the list is sorted already.

def next_greatest_letter(letters, target):
    letters.sort()
    for letter in letters:
        if letter > target:
            return letter
    return letters[0]

# Example usage:
letters = ["a", "f", "d", "b"]
target = "a"
result = next_greatest_letter(letters, target)
print(result)  # Output: 'f'

  #linear search takes o(n) time.  
 

b


In [2]:
# binary search approach
def binary_search(arr, target):
    left = 0
    right = len(arr) - 1
    while left <= right:
        mid = (left + right) // 2
        if arr[mid] < target:
            left = mid + 1
        else: 
            right = mid - 1
    return arr[left % len(arr)]
letters = ['a', 'b', 'd', 'h', 'k', 'm']
target = 'g'
out = binary_search(letters, target)
out


'h'

In [2]:
# binary search approach for efficiency
#If the list is large, a binary search approach would be more efficient with O(log n) time complexity
def binary_search(arr, target):
    left = 0
    right = len(arr) - 1
    while left <= right:
        mid = (left + right) // 2

        if arr[mid] > target:
            right = mid - 1
        else:
            left = mid + 1
    return arr[left % len(arr)]
arr = [2,3,4,5,6,7,8,9]
target = 4
out = binary_search(arr, target)
out



5

In [7]:
# check if N and its double exists
# Given an array of integers, check if there exist two indices i and j such that :

# Input: arr = [10,2,5,3]
# Output: true
# Explanation: For i = 0 and j = 2, arr[i] == 10 == 2 * 5 == 2 * arr[j]

arr = [10, 2, 5, 4]

for i in range(0, len(arr)):
    if arr[i] / 2 in arr:

        print('true')
        print(arr[i])
    else:
        print('false')

    
        









true
10
false
false
true
4


In [6]:
# valid mountain array

a = [0,3,4,6,8,7,6,5,4,1]
for i in range(len(a)):
    if a[i] > a[i - 1]  and a[i] > a[i + 1]:
        print('found mountain array, the number is',a[i])
    else:
        print('false')



    

false
false
false
false
found mountain array, the number is 8
false
false
false
false
false


In [3]:
#Given an Array of integers, return an Array where every element at an even-indexed position is squared.

# Input: array = [9, -2, -9, 11, 56, -12, -3]
# Output: [81, -2, 81, 11, 3136, -12, 9]

#Explanation: The numbers at even indexes (0, 2, 4, 6) have been squared, 

# whereas the numbers at odd indexes (1, 3, 5) have been left the same.

def even_index_square(arr):
    arr_new = []
    for i in range(len(arr)):
        if i % 2 == 0:
            arr[i] = arr[i] ** 2
        arr_new.append(arr[i])
    print(arr)


arr = [9, -2, -9, 11, 56, -12, -3]
even_index_square(arr)
    
        


[81, -2, 81, 11, 3136, -12, 9]


In [4]:
# this approach is inefficient because this takes o(length) extra space.
#better approach would be doing this inplace.

def even_square_index(arr):
    for i in range(0, len(arr), 2):
        arr[i] = arr[i]**2
    return arr

arr = [9, -2, -9, 11, 56, -12, -3]

arr = even_square_index(arr)
arr
        
        

[81, -2, 81, 11, 3136, -12, 9]

In [31]:
# Given an array arr, replace every element in that array with the greatest element among the elements to its right, and replace the last element with -1.

#Input: arr = [17,18,5,4,6,1]

#Output: [18,6,6,6,1,-1]

#Explanation:
 
#index 0 --> the greatest element to the right of index 0 is index 1 (18).
#index 1 --> the greatest element to the right of index 1 is index 4 (6).
#index 2 --> the greatest element to the right of index 2 is index 4 (6).
#index 3 --> the greatest element to the right of index 3 is index 4 (6).
#index 4 --> the greatest element to the right of index 4 is index 5 (1).
#index 517 --> there are no elements to the right of index 5, so we put -1.


# Input: arr = [400]
#Output: [-1]
#Explanation: There are no elements to the right of index 0.



import numpy as np

def find_greatest_right(arr):

    if len(arr) == 1:
            
            return -1


    for i in range(len(arr) -1):
        
        arr[i] = max(arr[i+1:])
    return arr

arr = [17,2,18,6,9,3,8,1]
# print(arr[0:])


output = find_greatest_right(arr)
print(output)






[18, 18, 9, 9, 8, 8, 1, 1]


In [51]:
from collections import Counter
# Given a sorted array, remove the duplicates such that each element appears only once.
#Input: array = [1, 1, 2]
#Output: [1, 2]

array = [0, 0, 1, 1, 1, 2, 2, 3, 3, 4]
Output: [0, 1, 2, 3, 4]

counter = Counter(array)
keys = counter.keys()
dict_to_list = list(keys)
dict_to_list







[0, 1, 2, 3, 4]

In [60]:
# another approach
arr = [0, 0, 1, 1, 1, 2, 2, 3, 3, 4, 4, 4]
def remove_duplicate(arr):
    dict = {}
    for i in arr:
        if i in dict:
            dict[i] += 1
        else:

            dict[i] = 1
        
    return dict

dict = remove_duplicate(arr)
keys = dict.keys()
unique_list = list(keys)
print(unique_list)




[0, 1, 2, 3, 4]


In [84]:
# Given an integer array nums sorted in non-decreasing order, remove the duplicates in-place such that each unique element appears only once. 
# The relative order of the elements should be kept the same. Then return the number of unique elements in nums.

#Input: nums = [0,0,1,1,1,2,2,3,3,4]
#Output: 5, nums = [0,1,2,3,4,_,_,_,_,_]

#Explanation: Your function should return k = 5, with the first five elements of nums being 0, 1, 2, 3, and 4 respectively.
#It does not matter what you leave beyond the returned k (hence they are underscores).

def remove_duplicate_inplace(nums):

    dict = {}
    result = []
    # count occurances of each element 
    for i in nums:
        if i in dict:
            dict[i]+= 1
        else:
            dict[i] = 1

    result = list(dict.keys())
    

    # iterate over the dict
    for i, count in dict.items():
        if count > 1:
            result.extend(('_') * (count - 1))
    return result
        

nums = [0,0,1,1,1,2,2,3,3,4]

out = remove_duplicate_inplace(nums)

out

        

[0, 1, 2, 3, 4, '_', '_', '_', '_', '_']

In [10]:
# move zeros
#Given an integer array nums, move all 0's to the end of it while maintaining the relative order of the non-zero elements.

#Note that you must do this in-place without making a copy of the array.
# A two-pointer approach could be helpful here. The idea would be to have one pointer for iterating the array and another pointer that just works on the non-zero elements of the array.

nums = [0,1,0,3,12]
Output = [1,3,12,0,0]
zeros = []
non_zeros = []

for i in nums:
    if i == 0:
        zeros.append(i)
    else:
        non_zeros.append(i)
non_zeros.extend(zeros)
print(non_zeros)
# in this approach both space complexity and time complexity are O(n)


[1, 3, 12, 0, 0]


In [12]:
# another approach which space complexity is o(1) and time complexity is o(n)
def move_zeros(nums):
    non_zeros = [i for i in nums if i == 0]
    zeros = [i for i in nums if i != 0]
    nums[:] = zeros + non_zeros
    return nums
nums = [0,1,0,3,12]
move_zeros(nums)

[1, 3, 12, 0, 0]

In [3]:
# Given an integer array nums, move all the even integers at the beginning of the array followed by all the odd integers.

# Input: nums = [3,1,2,4]
Output: [2,4,3,1]
#Explanation: The outputs [4,2,3,1], [2,4,1,3], and [4,2,1,3] would also be accepted.
def even_odd(nums):
    even_nums = [i for i in nums if i % 2 == 0]
    odd_nums = [i for i in nums if i % 2 != 0]
    nums = even_nums + odd_nums
    return nums
nums = [3,1,2,4]
out = even_odd(nums)
out


[2, 4, 3, 1]

In [3]:
#Input: nums = [3,2,2,3], val = 3
#Output: 2, nums = [2,2,_,_]
#Explanation: Your function should return k = 2, with the first two elements of nums being 2.
#It does not matter what you leave beyond the returned k (hence they are underscores).

#Input: nums = [0,1,2,2,3,0,4,2], val = 2
#Output: 5, nums = [0,1,4,0,3,_,_,_]
#Explanation: Your function should return k = 5, with the first five elements of nums containing 0, 0, 1, 3, and 4.
#Note that the five elements can be returned in any order.
#It does not matter what you leave beyond the returned k (hence they are underscores).

count = 0
val = 2
nums = [0,1,2,2,3,0,4,2]
out = []
for i in nums:
    if i == val:
        count +=1
    else:
        out.append(i)
out.extend(('_') * count)
print(out)
    









[0, 1, 3, 0, 4, '_', '_', '_']


In [16]:
# A school is trying to take an annual photo of all the students. The students are asked to stand in a single file line in non-decreasing order by height. Let this ordering be represented by the integer array expected where expected[i] is the expected height of the ith student in line.

# You are given an integer array heights representing the current order that the students are standing in. Each heights[i] is the height of the ith student in line (0-indexed).

# Return the number of indices where heights[i] != expected[i].
#Output: 3
#expected: [1,1,1,2,3,4]

#Indices 2, 4, and 5 do not match.

# heights.sort()
# print(heights)



heights = [1,1,4,2,1,3]

sorted_height = sorted(heights)
print(sorted_height)
count = 0
for i in range(len(heights)):
    if heights[i] != sorted_height[i]:
    
        count += 1

        print(f' the wrong number is {heights[i]}')
print(f' sum of wrong index are :{count}')




[1, 1, 1, 2, 3, 4]
 the wrong number is 4
 the wrong number is 1
 the wrong number is 3
 sum of wrong index are :3


In [ ]:
#   Third Maximum Number

# Given an integer array nums, return the third distinct maximum number in this array. If the third maximum does not exist, return the maximum number.
nums = [3,2,1]
Output: 1
Explanation:
# The first distinct maximum is 3.
# The second distinct maximum is 2.
# The third distinct maximum is 1.

nums = [1,2]
Output: 2
# Explanation:
# The first distinct maximum is 2.
# The second distinct maximum is 1.
# The third distinct maximum does not exist, so the maximum (2) is returned instead.

In [20]:
nums = [2, 1, 3]
for i in nums:
    for j in nums[]
    max[nums]


max_num = max(nums)
print(max_num)



3


3

In [15]:
# Given an array nums of n integers where nums[i] is in the range [1, n], return an array of all the integers in the range [1, n] that do not appear in nums.
nums = [4,3,2,7,8,2,3,1]
Output = [5,6]
l = []
for i in range(1, len(nums)+1):

    if i not in nums:
        l.append(i)
print(l)

[5, 6]


In [17]:
nums = [1, 1]
l = []
for i in range(1, len(nums) + 1):
    if i not in nums:
        l.append(i)
print(l)

[2]


In [22]:
#Given an integer array nums sorted in non-decreasing order, return an array of the squares of each number sorted in non-decreasing order.

nums = [-4,-1,0,3,10]
# nums2 = [-7,-3,2,3,11]
#Output: [0,1,9,16,100]
#Explanation: After squaring, the array becomes [16,1,0,9,100].
#After sorting, it becomes [0,1,9,16,100].
l = []
for i in nums:
    i_squared = i ** 2
    l.append(i_squared)

l.sort()
print(l)




[0, 1, 9, 16, 100]


In [23]:
nums = [-7,-3,2,3,11]
# Output: [4,9,9,49,121]
l = []
for i in nums:
    i_squared = i ** 2
    l.append(i_squared)

l.sort()
print(l)




[4, 9, 9, 49, 121]


In [28]:
def combine_arr1_arr2(arr1, arr2):

    i = 0
    j = 0
    l = []

    while i < len(arr1) and j < len(arr2):
        if arr1[i] < arr2[j]:
            l.append(arr1[i])
            i += 1
        else:
            l.append(arr2[j])
            j += 1

    while i < len(arr1):
        l.append(arr1[i])
        i += 1
    return l


arr1 = [1, 4, 7, 20, 23]
arr2 = [3, 5, 6, 8]

l = combine_arr1_arr2(arr1, arr2)
print(l)



[1, 3, 4, 5, 6, 7, 8, 20, 23]


In [36]:
# Example 1: Given a string s, return true if it is a palindrome, false otherwise.

# A string is a palindrome if it reads the same forward as backward. That means, after reversing it, it is still the same string. For example: "abcdcba", or "racecar".

s = 'abcdcba'
#s1 = racecar

def find_palindrome(s):
    for i in range(len(s) // 2):

        if s[i] != s[len(s) - i - 1]:
            return False
            
            
    return True
            
        
d = find_palindrome(s)
d
    

    

True

In [6]:
# Example 2: Given a sorted array of unique integers and a target integer, return true if there exists a pair of numbers that sum to target, false otherwise. This problem is similar to Two Sum. (In Two Sum, the input is not sorted).

#For example, given nums = [1, 2, 4, 6, 8, 9, 14, 15] and target = 13, return true because 4 + 9 = 13
target = 26
def find_pairs(nums):
    right = 0
    left = len(nums) - 1
    while right < left:
        curr = nums[right] + nums[left]
        if curr == target:
            return True
        if curr > target:
            left -= 1
        else:
            right += 1
    return False

nums = [1, 2, 4, 6, 8, 9, 14, 15]
out = find_pairs(nums)
out


    



False

In [14]:
# GivenGiven two strings s and t, return true if s is a subsequence of t, or false otherwise.

# A subsequence of a string is a sequence of characters that can be obtained by deleting some (or none) of the characters from the original string, while maintaining 
#the relative order of the remaining characters. For example, "ace" is a subsequence of "abcde" while "aec" is not.


#two strings s and t, return true if s is a subsequence of t, or false otherwise.

# A subsequence of a string is a sequence of characters that can be obtained by deleting some (or none) of the characters from the original string, while maintaining 
#the relative order of the remaining characters. For example, "ace" is a subsequence of "abcde" while "aec" is not.



s = 'tyh'
t = 'abcde'

def find_sub(s, t):
    i = 0
    j = 0

    while i < len(s) and j < len(t):
            

            if s[i] == t[j]:
                i+=1
            
            j+=1
    return i == len(s)
out = find_sub(s, t)
out
                

            
        

                
        
        
        
                    



False

In [7]:
sub = 'uen'
main_string = 'subsequent'
def find_subsequent(sub, main_string):
    i = 0
    j = 0

    while i < len(sub) and j < len(main_string):
        if sub[i] == main_string[j]:
            i+=1
        j+=1
    return i == len(sub)
result = find_subsequent(sub, main_string)
result




True

In [9]:
# i want to know if one string is exactly part of another string with the same order
sub = 'ston'
main_string = 'shingelton'

if sub in main_string:
    print(f' yesss string is subsequent')
else:

    print('No not subsequent')




No not subsequent


In [3]:
# find pivot index
#the pivot index is the index where the sum of all the numbers strictly to the left of the index is equal to the sum of all the numbers strictly to the index's right.

nums = [1,7,3,6,5,6]
# index = 3 is pivot index because nums[3] = 6 and from right hand side and left hand side of 6 the sum of all elements are the same 
# left hand side of 6 --> 1 + 7 + 3 = 11
# right hand side of 6 --> 5 + 6 = 11

for i in range(len(nums)):
    if sum(nums[:i]) == sum(nums[i + 1:]):
        print(f'the pivot index is :{i}')
    

the pivot index is :3


In [1]:
# diagonal traverse
# Given an m x n matrix mat, return an array of all the elements of the array in a diagonal order.

import numpy as np

mat = [[1,2,3],[4,5,6],[7,8,9]]
Output: [1,2,4,7,5,3,6,8,9]

nums = np.array(mat)
nums
print(len(nums))
print(nums)
print(nums[0][0])
print(nums[0][1])

3
[[1 2 3]
 [4 5 6]
 [7 8 9]]
1
2


In [22]:
# for i in range(len(nums)):
print(nums[0][0])
print(nums[1][0])
print(nums[0][1])

1
4
2


In [12]:
def find_diagonals(matrix):
    # if not matrix or not matrix[0]:
    #     return []

    diagonals = {}
    rows, cols = len(matrix), len(matrix[0])

    for i in range(rows):
        for j in range(cols):
            if i + j not in diagonals:
                diagonals[i + j] = []
            diagonals[i + j].append(matrix[i][j])

    # Print the diagonals
    for k in sorted(diagonals.keys()):
        print(f"Diagonal {k}: {diagonals[k]}")
find_diagonals(nums)

        





    

Diagonal 0: [1]
Diagonal 1: [2, 4]
Diagonal 2: [3, 5, 7]
Diagonal 3: [6, 8]
Diagonal 4: [9]


In [2]:
diagonals = {}
my_list = []
for i in range(len(nums)):
    for j in range(len(nums)):
        print(nums[i][j])
        if i + j not in diagonals:

            diagonals[i + j] = []
        diagonals[i + j].append(nums[i][j])
print(diagonals)

for k in sorted(diagonals.keys()):
    if k %2 == 0:
        diagonals[k].sort(reverse = True)
    my_list.extend(diagonals[k])
print(my_list)
    


1
2
3
4
5
6
7
8
9
{0: [1], 1: [2, 4], 2: [3, 5, 7], 3: [6, 8], 4: [9]}
[1, 2, 4, 7, 5, 3, 6, 8, 9]


In [1]:
import numpy as np
# spiral matrix
# Given an m x n matrix, return all elements of the matrix in spiral order.
matrix = [[1,2,3],[4,5,6],[7,8,9]]
Output = [1,2,3,6,9,8,7,4,5]
matrix = np.array(matrix)
print(matrix)
print(len(matrix))


[[1 2 3]
 [4 5 6]
 [7 8 9]]
3


In [9]:

def spiral_order(matrix):
    if not matrix or not matrix[0]:
        return []

    left = 0
    right = len(matrix[0]) - 1
    top = 0
    bottom = len(matrix) - 1
    result = []

    while left <= right and top <= bottom:
        # Traverse from left to right along the top row
        for j in range(left, right + 1):
            result.append(matrix[top][j])
        top += 1  # Move the top boundary down

        # Traverse from top to bottom along the right column
        for i in range(top, bottom + 1):
            result.append(matrix[i][right])
        right -= 1  # Move the right boundary left

        if top <= bottom:
            # Traverse from right to left along the bottom row
            for j in range(right, left - 1, -1):
                result.append(matrix[bottom][j])
            bottom -= 1  # Move the bottom boundary up

        if left <= right:
            # Traverse from bottom to top along the left column
            for i in range(bottom, top - 1, -1):
                result.append(matrix[i][left])
            left += 1  # Move the left boundary right

    return result

# Example matrix
matrix = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

result = spiral_order(matrix)
print(result)
        





        


[1, 2, 3, 6, 9, 8, 7, 4, 5]


In [1]:
Output = [[1],[1,1],[1,2,1],[1,3,3,1],[1,4,6,4,1]]

# pascal triangle
#Given an integer numRows, return the first numRows of Pascal's triangle.

#In Pascal's triangle, each number is the sum of the two numbers directly above it as shown:

numrows = 5

def generate_pascal_triangle(numrows):
    if numrows == 0:
        return []
    
    triangle = [[1]] # initialize the triangle

    for i in range(numrows):
        prev_row = triangle[-1]
        new_row = [1]
        for j in range(1, i):
            new_row.append(prev_row[j - 1] + prev_row[j])
        new_row.append(1)
        triangle.append(new_row)
    return triangle
tri = generate_pascal_triangle(5)
tri




[[1], [1, 1], [1, 1], [1, 2, 1], [1, 3, 3, 1], [1, 4, 6, 4, 1]]

In [4]:
Output = [[1],[1,1],[1,2,1],[1,3,3,1],[1,4,6,4,1]]

def generate_pascals_triangle(numRows):
    if numRows == 0:
        return []
    
    triangle = [[1]]  # Initialize with the first row
    
    for i in range(1, numRows):
        prev_row = triangle[-1]              # Get the last row from the triangle
        new_row = [1]                        # Start with 1
        
        # Compute the values for the new row
        for j in range(1, i):
            new_row.append(prev_row[j - 1] + prev_row[j])
        
        new_row.append(1)                     # End with 1
        triangle.append(new_row)              # Add the new row to the triangle
    
    return triangle

# Example usage:
numRows = 5
print(generate_pascals_triangle(numRows))

[[1], [1, 1], [1, 2, 1], [1, 3, 3, 1], [1, 4, 6, 4, 1]]
