In [1]:
# knn classifies the data point based on how their are classified

x = [3,4,5,6,7]
x[::-1]

[7, 6, 5, 4, 3]

In [2]:
x[:-1]

[3, 4, 5, 6]

In [3]:
x[:-2]

[3, 4, 5]

In [6]:
for i in x[:-2]:
    
    
    print(i)

3
4
5


In [9]:
x[::-1]

TypeError: list indices must be integers or slices, not tuple

In [8]:
x[::-1]

[7, 6, 5, 4, 3]

In [11]:
x[:-2]

[3, 4, 5]

In [12]:
x[4:]

[7]

In [13]:
x[4]

7

In [14]:
x[3:]

[6, 7]

In [19]:
import numpy as np
x_1 = [1,1,1,1,1,1]
x_2 = [1,1,2,2,2,2]
d = np.linalg.norm(x_1, x_2)
d


array([6.        , 6.        , 2.44948974, 2.44948974, 2.44948974,
       2.44948974])

In [26]:
x = np.array([9,7,3,4,5,6])
x.argsort()

array([2, 3, 4, 5, 1, 0])

In [27]:
x.argsort()[:2]

array([2, 3])

In [28]:
np.argsort(x)

array([2, 3, 4, 5, 1, 0])

In [29]:
np.argsort(-x)

array([0, 1, 5, 4, 3, 2])

In [30]:
np.argsort(x)[::-1]

array([0, 1, 5, 4, 3, 2])

In [31]:
y_train = np.array([0, 1, 1, 0])
indices = [1, 2]
y_train[indices]

array([1, 1])

In [32]:
y_train[[0,1]]

array([0, 1])

In [35]:
X_train = np.array([[1,2],
                  [3,4],
                  [5,5],
                  [10,10]])

y_train = np.array([0, 1, 1, 0])


In [37]:
x_new = np.array([4,4])

distance = np.linalg.norm(X_train - x_new, axis=1)
distance

array([3.60555128, 1.        , 1.41421356, 8.48528137])

In [38]:
np.argsort(distance)

array([1, 2, 0, 3])

In [41]:
k = 2  #k nearest neighbors

nearest_indices = np.argsort(distance)[:k]
nearest_labels = y_train[nearest_indices]
nearest_labels

array([1, 1])

In [49]:
from collections import Counter

class KnearestNeighbor:
    
    def __init__(self, k=2):
        self.k = k

    def fit(self, X,y):

        self.X_train = X
        self.y_train = y
        


    def predict(self, X):
        
        return np.array([self.predict_point(x) for x in X])


    def predict_point(self, x):
        
        distances = np.linalg.norm(self.X_train - x, axis=1)
        k_indices = np.argsort(distances)[:self.k]
        k_nearest_labels = self.y_train[k_indices]
        most_common = Counter(k_nearest_labels).most_common(1)[0][0]
        
        return most_common






X = np.array([[1,2],[3,4],[5,5],[10,10]])

y = np.array([0, 1, 1, 0])

knn = KnearestNeighbor()
knn.fit(X,y)
predicted_label = knn.predict(np.array([4,4]))
predicted_label

        
        
        

array([1, 1])

In [58]:
from sklearn.neighbors import KNeighborsClassifier

X = np.array([[1,2],[3,4],[5,5],[10,10]])

y = np.array([0, 1, 1, 0])


knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X, y)
pred_labels = knn.predict(np.array([4, 4]).reshape(1, -1))
pred_labels

array([1])