In [ ]:
#create bootstrap dataset from the original dtaset
# train decision tree on each bootstraped dtaaset and for this we use decision tree from sklearn 
#combine the predictions using majority voting

In [27]:
import numpy as np
from sklearn.tree import DecisionTreeClassifier
from collections import Counter

In [28]:


X = np.array([[1,1],
             [1,2],
             [2,1],
             [2,2],
             [3,1],
             [3,2],
             [4,1],
             [4,2]])

y = np.array([0,0,0,0,1,1,1,1])

In [29]:
def bootstrap_sample(X, y):
    n_sample = X.shape[0]
    indices = np.random.choice(n_sample, size=n_sample, replace=True)
    return X[indices], y[indices]
    # print(indices)
    # print(X[indices])
    # print(y[indices])

In [30]:
#train multiple decision tree on bootstraped samples

def train_bagging(X, y, n_estimators=5):
    trees = []
    for i  in range(n_estimators):
        X_sample, y_sample = bootstrap_sample(X, y)
        tree = DecisionTreeClassifier()
        tree.fit(X_sample, y_sample)
        trees.append(tree)
    return trees
    

In [44]:
#predict by majority voting
def predict_bagging(X, trees):
    #collect predictions from each tree
    preds = np.array([tree.predict(X) for tree in trees])
    preds = preds.T
    y_pred = []
    for pred in preds:
        vote = Counter(pred).most_common(1)[0][0]
        y_pred.append(vote)
    return np.array(y_pred)

trees = train_bagging(X,y, n_estimators=5)
predictions = predict_bagging(X,trees)
print(predictions)

        
    

[0 0 0 0 1 1 1 1]


In [6]:
X.shape[0]

8

In [ ]:
n_sample = X.shape[0]

In [9]:
np.arange(4)

array([0, 1, 2, 3])

In [11]:
np.random.choice(5,6)

array([1, 3, 2, 4, 4, 1])

In [36]:
np.array(np.int64(0))

array(0)

In [47]:
X = np.array([[1,0],
            [1,1],
            [2,1],
            [2,2],
            [3,1],
            [3,2],
            [4,1],
            [4,2]])
y = np.array([0, 0, 0, 0, 1, 1, 1, 1])
X.shape




(8, 2)

In [49]:
n_samples = X.shape[0]
indices = np.random.choice(n_samples, size=n_samples, replace=True)
indices

array([7, 0, 3, 4, 6, 0, 2, 2])

In [50]:
def bootstrap_sample(X, y):
    
    n_estimators = 5
    
    for i in range(n_estimators):
        indices = np.random.choice(n_samples, size=n_samples, replace=True)
        return X[indices], y[indices]

[[1 2]
 [1 2]
 [4 2]
 [3 2]
 [4 2]
 [1 2]
 [1 2]
 [2 1]] [0 0 1 1 1 0 0 0]
[[4 1]
 [1 1]
 [4 2]
 [4 1]
 [1 2]
 [2 1]
 [3 1]
 [2 1]] [1 0 1 1 0 0 1 0]
[[3 2]
 [2 1]
 [3 2]
 [1 2]
 [2 1]
 [4 1]
 [2 2]
 [1 2]] [1 0 1 0 0 1 0 0]
[[2 2]
 [1 2]
 [2 1]
 [1 1]
 [3 2]
 [4 1]
 [3 2]
 [2 1]] [0 0 0 0 1 1 1 0]
[[1 2]
 [3 1]
 [3 2]
 [3 1]
 [3 2]
 [4 2]
 [3 1]
 [1 2]] [0 1 1 1 1 1 1 0]


In [81]:
def build_trees(X, y):
    trees = []
    for i in range(n_estimators):
        bootstraped_X, bootstraped_y = bootstrap_sample(X, y)
        tree = DecisionTreeClassifier()
        tree.fit(bootstraped_X, bootstraped_y)
        trees.append(tree)
    return trees

trees = build_trees(X, y)
        

In [82]:
n_samples = X_n.shape[0]
indices = np.random.choice(n_samples, size=n_samples, replace=True)
indices

array([3, 0, 2, 1])

In [83]:
def predict_bagging(trees, X):
    #collect predictions
    y_pred = []
    preds = np.array([tree.predict(X) for tree in trees])
    preds = preds.T
    for pred in preds:
        vote = Counter(pred).most_common(1)[0][0]
        # print(vote)
        y_pred.append(vote)
    return np.array(y_pred)
    
X_n = np.array([[1,0],[1,1],[2,0], [2,1]])
y_n = np.array([0, 0, 1, 1])
predictions = predict_bagging(trees, X)
predictions

array([0, 0, 1, 1])